### ISSUE TITLE
Get Document List

### ISSUE THREAD

**Issue by SimonGeering** [SimonGeering/AdminAssistant#124]
### Tasks

**Client Side** 
- [ ] UX Design
- [ ] Blazor UI Prototype
- [ ] WPF UI Prototype
- [ ] Acceptance Test
- [ ] Blazor UI implementation
- [ ] WPF UI implementation
- [ ] UI View Model & Unit Test
- [x] UI Service & Unit Test
- [x] REST API client, TypeMapping & UnitTest

**Server Side**
- [ ] REST API Integration Test
- [x] REST API Controler, TypeMapping & Unit Test inc 
- [x] Domain MediatR Query & Unit Test
- [ ] DAL Repository, Specification & Unit Test
- [ ] DAL EF Schema Definition, TypeMapping
