### ISSUE TITLE
Create/Update Bank Account

### ISSUE THREAD

**Issue by SimonGeering** [SimonGeering/AdminAssistant#31]
### Tasks

**Client Side** 
- [x] UX Design
- [x] Blazor UI Prototype
- [x] WPF UI Prototype
- [ ] Acceptance Test
- [ ] Blazor UI implementation
- [ ] WPF UI implementation
- [ ] UI View Model & Unit Test
- [ ] UI Service & Unit Test
- [ ] REST API client, TypeMapping & UnitTest

**Server Side**
- [ ] REST API Integration Test
- [ ] REST API Controler, TypeMapping & Unit Test inc 
- [ ] Domain MediatR Query & Unit Test
- [ ] Domain Validator & Unit Test
- [ ] DAL Repository, Specification & Unit Test
- [ ] DAL EF Schema Definition, TypeMapping
