### ISSUE TITLE
Create/Update Bank

### ISSUE THREAD

**Issue by SimonGeering** [SimonGeering/AdminAssistant#73]
### Tasks

**Client Side** 
- [ ] UX Design
- [ ] Blazor UI Prototype
- [ ] WPF UI Prototype
- [ ] Acceptance Test
- [ ] Blazor UI implementation
- [ ] WPF UI implementation
- [ ] UI View Model & Unit Test
- [ ] UI Service & Unit Test
- [ ] REST API client, TypeMapping & UnitTest

**Server Side**
- [ ] REST API Integration Test
- [x] REST API Controler, TypeMapping & Unit Test inc 
- [x] Domain MediatR Query & Unit Test
- [x] Domain Validator & Unit Test
- [x] DAL Repository, Specification & Unit Test
- [x] DAL EF Schema Definition, TypeMapping
