### ISSUE TITLE
Get Currencies List

### ISSUE THREAD

**Issue by SimonGeering** [SimonGeering/AdminAssistant#74]
### Tasks

**Client Side** 
- [x] UI Service & Unit Test
- [x] REST API client, TypeMapping & UnitTest

**Server Side**
- [x] REST API Integration Test
- [x] REST API Controler, TypeMapping & Unit Test inc 
- [x] Domain MediatR Query & Unit Test
- [x] DAL Repository, Specification & Unit Test
- [x] DAL EF Schema Definition, TypeMapping
